export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',
  PROFILE_INCOMPLETE: 'PROFILE_INCOMPLETE',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  INVITE_INVALID: 'INVITE_INVALID',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
};
